const translates = {
    en: {
        en: 'English',
        ru: 'Russian',
        uz: 'Uzbek',
        headerNews: 'NEWSLETTERS',
        navLiHouse: 'HOUSE TOURS',
        navLiStyle: 'STYLE',
        navLiHow: 'HOW TO',
        navLiOrganize: 'ORGANIZE & CLEAN',
        navLiLiving: 'LIVING',
        navLiShop: 'SHOP',
        navLiMore: 'MORE',
        heroArticleType: 'TOUR',
        heroArticleTitle: '9 Things You Learn Living in a Tiny Studio Apartment',
        heroArticleAuthor: 'by Adrienne Breaux',
        heroArticleDate: 'Yesterday',
    },
    ru: {
        en: 'Английский',
        ru: 'Русский',
        uz: 'Узбекский',
        headerNews: 'БЮЛЛЕТЕНИ',
        navLiHouse: 'ДОМАШНИЕ ТУРЫ ',
        navLiStyle: 'СТИЛЬ',
        navLiHow: 'КАК',
        navLiOrganize: 'ОРГАНИЗИРОВАТЬ И ОЧИСТИТЬ',
        navLiLiving: 'ЖИЗНЬ',
        navLiShop: 'МАГАЗИН',
        navLiMore: 'БОЛЬШЕ',
        heroArticleType: 'ТУР',
        heroArticleTitle: '9 вещей, которые вы узнаете, пока будете жить в крохотной однокомнатной квартире',
        heroArticleAuthor: 'Адриенн Бро',
        heroArticleDate: 'Вчера',
    },
    uz: {
        en: 'Ingliz',
        ru: 'Rus',
        uz: 'O\'zbek',
        headerNews: 'XABARLAR',
        navLiHouse: 'UY TURLARI',
        navLiStyle: 'STIL',
        navLiHow: 'QANDAY',
        navLiOrganize: 'TASHKIL ETISH VA TOZALIK',
        navLiLiving: 'YASHASH',
        navLiShop: 'DO\'KON',
        navLiMore: 'KO\'PROQ',
        hAeroArticleType: 'TUR',
        heroArticleTitle: 'Kichkina studiya kvartirasida yashab o\'rganish mumkin bo\'lgan 9 narsa',
        heroArticleAuthor: 'Adrienne Breaux tomonidan',
        heroArticleDate: 'Kecha',
    },
}

export default translates
