const translates = {
    en: {
        en: 'English',
        ru: 'Russian',
        uz: 'Uzbek',
        headerNews: 'NEWSLETTERS',
        navLiHouse: 'HOUSE TOURS',
        navLiStyle: 'STYLE',
        navLiHow: 'HOW TO',
        navLiOrganize: 'ORGANIZE & CLEAN',
        navLiLiving: 'LIVING',
        navLiShop: 'SHOP',
        navLiMore: 'MORE',
        heroArticleType: 'TOUR',
        heroArticleTitle: '9 Things You Learn Living in a Tiny Studio Apartment',
        heroArticleAuthor: 'by Adrienne Breaux',
        heroArticleDate: 'Yesterday',
        articleOneTitle: 'An Architect Redesigned the Harry Potter Book Covers to Feature Modernist Designs',
        articleOneDesc: 'When the Italian publishing house Salani commissioned architect Michele De Lucchi and his AMDL CIRCLE studio to redesign the Italian versions of the iconic book covers of the “Harry Potter” series, De Lucchi did what he does best and focused his attention on reimagining the fantastical buildings of the wizarding world in a contemporary style.',
        articleOneAuthor: 'by Olivia Harvey',
        articleOneDate: 'May 23, 2021',
        articleTwoTitle: '5 Questions People Forget to Ask Realtors Before Hiring Them',
        articleTwoDesc: 'In today’s competitive housing market, it’s more important than ever to make sure you’re working with the best realtor you can find. But just because you’ve found a great realtor, it doesn’t mean you’ll always be on the same page. Find out how well you’ll mesh with your prospective realtor by asking them these important (but oft forgotten) questions. ',
        articleTwoAuthor: 'by Lauren Wellbank',
        articleTwoDate: 'May 23, 2021',
        articleThreeTitle: '3 Airbnbs with Backyard Chess Boards That Will Bring Your “Queen’s Gambit” Fantasies to Life This Summer',
        articleThreeDesc: 'If you’ve played a game of chess in the last year, go ahead and mark off that space on your pandemic bingo card. “Queen’s Gambit,” a show about a spectacularly talented young girl chess player, shot the game into the spotlight last fall — and interest in it hasn’t waned since.',
        articleThreeAuthor: 'by Jennifer Billock',
        articleThreeDate: 'May 23, 2021',
    },
    ru: {
        en: 'Английский',
        ru: 'Русский',
        uz: 'Узбекский',
        headerNews: 'БЮЛЛЕТЕНИ',
        navLiHouse: 'ДОМАШНИЕ ТУРЫ ',
        navLiStyle: 'СТИЛЬ',
        navLiHow: 'КАК',
        navLiOrganize: 'ОРГАНИЗИРОВАТЬ И ОЧИСТИТЬ',
        navLiLiving: 'ЖИЗНЬ',
        navLiShop: 'МАГАЗИН',
        navLiMore: 'БОЛЬШЕ',
        heroArticleType: 'ТУР',
        heroArticleTitle: '9 вещей, которые вы узнаете, пока будете жить в крохотной однокомнатной квартире',
        heroArticleAuthor: 'Адриенн Бро',
        heroArticleDate: 'Вчера',
        articleOneTitle: 'Архитектор изменил дизайн обложек книг о Гарри Поттере, чтобы отразить модернистский дизайн',
        articleOneDesc: 'Когда итальянское издательство Salani поручило архитектору Микеле Де Луччи и его студии AMDL CIRCLE переработать итальянские версии обложек культовых книг из серии« Гарри Поттер », Де Луччи сделал то, что у него получается лучше всего, и сосредоточил свое внимание на переосмыслении фантастические постройки волшебного мира в современном стиле.',
        articleOneAuthor: 'Оливия Харви',
        articleOneDate: '23 мая 2021 года',
        articleTwoTitle: '5 вопросов, которые люди забывают задавать риэлторам, прежде чем нанять их',
        articleTwoDesc: 'На сегодняшнем конкурентном рынке жилья как никогда важно убедиться, что вы работаете с лучшим риэлтором, которого можете найти. Но то, что вы нашли хорошего риелтора, не означает, что вы всегда будете на одной волне. Узнайте, насколько хорошо вы будете взаимодействовать со своим потенциальным риелтором, задав им эти важные (но часто забываемые) вопросы.',
        articleTwoAuthor: 'Лорен Веллбанк',
        articleTwoDate: '23 мая 2021 года',
        articleThreeTitle: '3 Airbnb с шахматными досками на заднем дворе, которые воплотят в жизнь ваши фантазии о« ферзевом гамбите »этим летом',
        articleThreeDesc: 'Если вы играли в шахматы в прошлом году, отметьте это место на своей карточке пандемического бинго. «Ферзевый гамбит», шоу о невероятно талантливой девушке-шахматистке, привлекло внимание к этой игре прошлой осенью - и с тех пор интерес к ней не угас.',
        articleThreeAuthor: 'Дженнифер Биллок',
        articleThreeDate: '23 мая 2021 года',
    },
    uz: {
        en: 'Ingliz',
        ru: 'Rus',
        uz: 'O\'zbek',
        headerNews: 'XABARLAR',
        navLiHouse: 'UY TURLARI',
        navLiStyle: 'STIL',
        navLiHow: 'QANDAY',
        navLiOrganize: 'TASHKIL ETISH VA TOZALIK',
        navLiLiving: 'YASHASH',
        navLiShop: 'DO\'KON',
        navLiMore: 'KO\'PROQ',
        hAeroArticleType: 'TUR',
        heroArticleTitle: 'Kichkina studiya kvartirasida yashab o\'rganish mumkin bo\'lgan 9 narsa',
        heroArticleAuthor: 'Adrienne Breaux tomonidan',
        heroArticleDate: 'Kecha',
        articleOneTitle: 'Me\'mor Garri Potter kitobining muqovalarini modernistik dizaynlar asosida qayta ishladi',
        articleOneDesc: 'Italiyaning Salani nashriyoti me\'mor Mishel De Lucchi va uning AMDL CIRCLE studiyasiga "Garri Potter" turkumidagi ramziy kitob muqovalarining italyancha versiyasini qayta ishlashni buyurganida, De Lucchi qo\'lidan kelganicha ish olib bordi va diqqatini qayta tasavvur qilishga qaratdi. sehrgarlar dunyosining zamonaviy uslubdagi hayoliy binolari.',
        articleOneAuthor: 'Olivia Harvey tomonidan',
        articleOneDate: '2021 yil 23-may',
        articleTwoTitle: 'Odamlar ularni qabul qilishdan oldin rieltorlardan so\'rashni unutadigan 5 ta savol',
        articleTwoDesc: 'Bugungi raqobatbardosh uy-joy bozorida topishingiz mumkin bo\'lgan eng yaxshi rieltor bilan ishlashga ishonch hosil qilish har qachongidan ham muhimroq. Ammo siz ajoyib rieltorni topganingiz uchun, bu siz doimo bitta sahifada bo\'lishingizni anglatmaydi. Kelajakdagi rieltoringizga ushbu muhim (lekin tez-tez unutilgan) savollarni berib, qanchalik yaxshi ish tutishingizni bilib oling.',
        articleTwoAuthor: 'Lauren Wellbank tomonidan',
        articleTwoDate: '2021 yil 23-may',
        articleThreeTitle: 'Yozda sizning" qirolichangizning gambiti "fantaziyalarini hayotga olib keladigan orqa hovlisidagi shaxmat taxtalari bilan 3 ta Airbnbs',
        articleThreeDesc: 'Agar siz o\'tgan yili shaxmat o\'yinini o\'ynagan bo\'lsangiz, davom eting va pandemik bingo kartangizdagi joyni belgilang. "Qirolichaning Gambiti", ajoyib iste\'dodli yosh shaxmatchi qiz haqida namoyish, o\'tgan yilning kuzida o\'yinni diqqat markaziga tushirdi - va bundan buyon unga bo\'lgan qiziqish susaymadi. ',
        articleThreeAuthor: 'Jennifer Billock tomonidan',
        articleThreeDate: '2021 yil 23-may',
        
    },
}

export default translates
